version: "3.8"
services:
  db:
    image: postgis/postgis:15-3.4
    shm_size: 1gb
    environment:
      POSTGRES_USER: r2gg
      POSTGRES_PASSWORD: r2gg
      POSTGRES_DB: pivot_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  importer:
    build:
      context: ./docker/import
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PGUSER=r2gg
      - PGPASSWORD=r2gg
      - PGHOST=db
      - PGPORT=5432
      - SOURCE_DB=source_db
      - GPKG_URL=https://data.geopf.fr/telechargement/download/BDTOPO/BDTOPO_3-5_TRANSPORT_GPKG_LAMB93_FXX_2026-06-15/BDTOPO_3-5_TRANSPORT_GPKG_LAMB93_FXX_2026-06-15.7z
      - GPKG_IN_ARCHIVE=BDTOPO_3-5_TRANSPORT_GPKG_LAMB93_FXX_2026-06-15/BDTOPO_TRANSPORT/1_DONNEES_LIVRAISON_2026-06-00420/BDT_3-5_GPKG_LAMB93_FXX_ED2026-06-15/TRANSPORT/troncon_de_route.gpkg,BDTOPO_3-5_TRANSPORT_GPKG_LAMB93_FXX_2026-06-15/BDTOPO_TRANSPORT/1_DONNEES_LIVRAISON_2026-06-00420/BDT_3-5_GPKG_LAMB93_FXX_ED2026-06-15/TRANSPORT/non_communication.gpkg
    # importer script will run once to load the source DB

  r2gg:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: docker/debian/Dockerfile
    depends_on:
      db:
        condition: service_started
      importer:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://r2gg:r2gg@db:5432/pivot_db
    volumes:
      - ./:/user/app
      - /data/r2gg_output/generation:/home/docker/data/generation
    working_dir: /user/app
    command: >
      bash -c "
        r2gg-sql2pivot docker/config/bdtopo2valhalla_local.json &&
        r2gg-pivot2osm docker/config/bdtopo2valhalla_local.json &&
        r2gg-osm2valhalla docker/config/bdtopo2valhalla_local.json &&
        r2gg-road2config docker/config/bdtopo2valhalla_local.json
      "
    secrets:
      - db_config

  road2:
    build:
      context: ../road2/
      dockerfile: docker/distributions/debian/Dockerfile
    depends_on:
      r2gg:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - /data/r2gg_output/:/home/docker/data
      - ./docker/config:/home/docker/config

volumes:
  db_data:

secrets:
  db_config:
    file: ./docker/data/pivot_base.json
